variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - publish
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

Build Image:
  stage: build
  script:
    - docker build --cache-from --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

Test Image:
  stage: test
  script:
    - docker run -d -p'27014:27014' --rm -t "$CI_REGISTRY_IMAGE"
    - apk add --no-cache curl
    - sleep 15
    - docker ps
    - ip a
    #- curl 0.0.0.0:27014/ping

Docker.com:
  stage: publish
  script:
    - docker pull "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "spezifanta/source-monitor"
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker push "spezifanta/source-monitor"
