image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - publish
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

Build Image:
  stage: build
  script:
    - docker build --cache-from --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

Test Image:
  stage: test
  script:
    - docker run -d -p'27014:27014' --rm -t "$CI_REGISTRY_IMAGE"
    - apk add --no-cache curl
    - sleep 15
    - docker ps
    - ip a
    #- curl 0.0.0.0:27014/ping

Docker.com:
  stage: publish
  script:
    - docker pull "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "spezifanta/source-monitor"
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker push "spezifanta/source-monitor"
      #
      #GitHub.com:
      #  stage: publish
      #  when: manual
      #  script:
      #    - apk update
      #    - apk add openssh-client git
      #    - eval $(ssh-agent -s)
      #    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
      #    - mkdir -p ~/.ssh
      #    - chmod 700 ~/.ssh
      #    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      #    - chmod 600 ~/.ssh/config
      #    - git config --global user.email "alex@qrt.de"
      #    - git config --global user.name "Alex Kuhrt"
      #    - git remote add github ssh://git@github.com/spezifanta/hldm-docker.git
      #    - git push --force github master
      #
      #Update Gameserver:
      #  stage: deploy
      #  environment:
      #    name: SteamCalculator.com
      #  when: manual
      #  script:
      #    - apk add --no-cache openssh-client
      #    - eval $(ssh-agent -s)
      #    - echo "$ANSIBLE_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
      #    - ssh -tt -o StrictHostKeyChecking=no ansible@ansible.kuhrt.it -p222 'ansible-playbook -v steamcalculator.yml --tags="hlds"'
      #
